In [1]:
import numpy as np #mathematics
import matplotlib.pyplot as plt #like graph plot
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [9]:
# fitting the model for grid search
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
# GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

#classifier.predict([[40,30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[51  0]
 [ 0 82]]
The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

ROC AUC Score: 1.0


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [12]:
import pickle
filename="finalized_model_Gradient_boosting.sav"
pickle.dump(classifier,open(filename,'wb'))

In [14]:
loaded_model=pickle.load(open('finalized_model_Gradient_boosting.sav','rb'))
result=loaded_model.predict([[40,30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0]])

In [15]:
result

array([1])

In [17]:
age_input=float(input('Age:'))
bp_input=float(input("bp:"))
al_input=float(input("al:"))
su_input=float(input('su:'))
bgr_input=float(input('bgr:'))
bu_input=float(input('bu:'))
sc_input=float(input('sc:'))
sod_input=float(input('sod:'))
pot_input=float(input('pot:'))
hrmo_input=float(input('hrmo:'))
pcv_input=float(input('pcv:'))
wc_input=float(input('wc:'))
rc_input=float(input('rc:'))
sg_b_input=float(input('sg_b:'))
sg_c_input=float(input('sg_c:'))
sg_d_input=float(input('sg_d:'))
sg_e_input=float(input('sg_e:'))
rbc_normal=float(input('rbc_normal:'))
pc_normal=float(input('pc_normal:'))
pcc_present=float(input('pcc_present:'))
ba_present=float(input('ba_present:'))
htn_yes=float(input('htn_yes:'))
dm_yes=float(input('dm_yes:'))
cad_yes=float(input('cad_yes:'))
appet_yes=float(input('appet_yes:'))
pe_yes=float(input('pe_yes:'))
ane_yes=float(input('ane_yes:'))

Age:30
bp:40
al:1
su:1
bgr:1
bu:1
sc:1
sod:1
pot:1
hrmo:1
pcv:1
wc:1
rc:0
sg_b:0
sg_c:0
sg_d:0
sg_e:0
rbc_normal:0
pc_normal:0
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:1
appet_yes:1
pe_yes:1
ane_yes:1


In [19]:
Future_prediction=classifier.predict([[ age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,
                                 hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,
                                 rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[1]
