In [1]:
import numpy as np #mathematics
import matplotlib.pyplot as plt #like graph plot
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)        

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [8]:
independent.shape

(399, 27)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [10]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


The confusion matrix:
 [[51  0]
 [ 3 79]]
The report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

ROC AUC Score: 1.0


array([1])

In [11]:
from sklearn.naive_bayes import MultinomialNB
classifier= MultinomialNB()
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[50  1]
 [22 60]]
The report:
               precision    recall  f1-score   support

           0       0.69      0.98      0.81        51
           1       0.98      0.73      0.84        82

    accuracy                           0.83       133
   macro avg       0.84      0.86      0.83       133
weighted avg       0.87      0.83      0.83       133

ROC AUC Score: 0.9172644667623147


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1])

In [12]:
from sklearn.naive_bayes import BernoulliNB
classifier=  BernoulliNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[51  0]
 [ 9 73]]
The report:
               precision    recall  f1-score   support

           0       0.85      1.00      0.92        51
           1       1.00      0.89      0.94        82

    accuracy                           0.93       133
   macro avg       0.93      0.95      0.93       133
weighted avg       0.94      0.93      0.93       133

ROC AUC Score: 0.9991630798660928


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([1])

In [13]:
from sklearn.naive_bayes import CategoricalNB
classifier= CategoricalNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


IndexError: index 90 is out of bounds for axis 1 with size 84

In [15]:
from sklearn.naive_bayes import ComplementNB
classifier= ComplementNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[50  1]
 [22 60]]
The report:
               precision    recall  f1-score   support

           0       0.69      0.98      0.81        51
           1       0.98      0.73      0.84        82

    accuracy                           0.83       133
   macro avg       0.84      0.86      0.83       133
weighted avg       0.87      0.83      0.83       133

ROC AUC Score: 0.9172644667623147


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(


array([1])