In [1]:
import numpy as np #mathematics
import matplotlib.pyplot as plt #like graph plot
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)        

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [8]:
independent.shape

(399, 27)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [10]:
# fitting the model for grid search
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [22]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[51  0]
 [ 3 79]]
The report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

ROC AUC Score: 1.0


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [26]:
from sklearn.naive_bayes import MultinomialNB
classifier= MultinomialNB()
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Negative values in data passed to MultinomialNB (input X)

In [21]:
from sklearn.naive_bayes import BernoulliNB
classifier=  BernoulliNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

The confusion matrix:
 [[51  0]
 [ 1 81]]
The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC AUC Score: 0.9997608799617408


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [24]:
from sklearn.naive_bayes import CategoricalNB
classifier= CategoricalNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

from sklearn.metrics import roc_auc_score 
roc=roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])
print("ROC AUC Score:",roc)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Negative values in data passed to CategoricalNB (input X)

In [17]:
from sklearn.naive_bayes import ComplementNB
classifier= ComplementNB()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("The confusion matrix:\n",cm)

#Evolution 
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print("The report:\n",clf_report)

classifier.predict([[40,300,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Negative values in data passed to ComplementNB (input X)